import os

import pandas as pd
import numpy as np


# Defining the basic parameter sets for the different PMMA experiments.
class MaCFP_PMMA:
    """
    Contains information on PMMA samples from MaCFP (2020-03-04). 
    Note: Not all the information is reproduced here, if in doubt check 
    the respective entry in the Git repository at: 
    https://github.com/MaCFP/matl-db/tree/master/Non-charring/PMMA
    """

    # Experimental data.
    exp_data = {'TGA': {
            'SANDIA_STA_Ar_1': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 1.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 4.903, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_1.csv')},
            'SANDIA_STA_Ar_2': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 10.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 4.917, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_2.csv')},
            'SANDIA_STA_Ar_3': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 10.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 4.828, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_3.csv')},
            'SANDIA_STA_Ar_4': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 50.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 5.376, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_4.csv')},
            'SANDIA_STA_Ar_5': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 50.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 4.835, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_5.csv')},
            'SANDIA_STA_Ar_6': {'laboratory': 'Sandia National Laboratories', 
                                'heating_rate': {'value': 50.0, 'unit': 'K/min'},
                                'temperature_program': {'initial_temperature': {'value': 303.15, 'unit': 'K'},
                                                        'isotherm': {'value': 20.0, 'unit': 'min'},
                                                        'max_temperature': {'value': 873.15, 'unit': 'K'}},
                                'initial_sample_mass': {'value': 4.682, 'unit': 'mg'},
                                'sample_geometry': 'powdered',
                                'calibration_type': 'The instrument is calibrated at least once per 6 months, or sooner (as needed), using melting point standards for both temperature and DSC sensitivity. The calibration standards used are In, Sn, Bi, Zn, Al, Ag, Au, and Ni.',
                                'crucible_type': 'Al2O3 crucibles',
                                'crucible_volume': {'value': 85, 'unit': 'µL'},
                                'crucible_lids': False,
                                'carrier_gas_type': 'ultra-high-purity argon (0% O2)',
                                'carrier_gas_flow': {'value': 100, 'unit': 'ml/min'},
                                'instrument_type': 'Netzsch F3 Jupiter',
                                'path': os.path.join('Non-charring', 'PMMA', 'Sandia', 'SANDIA_TGA_Ar_6.csv')},
        'UMET_TGA_N2_1': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 1.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 4.336, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_1.csv')},
        'UMET_TGA_N2_2': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 2.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 4.845, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_2.csv')},
        'UMET_TGA_N2_3': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 5.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 4.093, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_3.csv')},
        'UMET_TGA_N2_4': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 10.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 5.339, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_4.csv')},
        'UMET_TGA_N2_5': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 20.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 3.929, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_5.csv')},
        'UMET_TGA_N2_6': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 50.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 5.980, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_6.csv')},
        'UMET_TGA_N2_7': {'laboratory': 'University of Lille - ENSCL',
                          'heating_rate': {'value': 100.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.15, 'unit': 'K'},
                                                  'isotherm': {'value': 20.0, 'unit': 'min'},
                                                  'max_temperature': {'value': 1273.15, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 5.364, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Temperature calibration was performed every 6 months using a set of 5 reference materials with melting temperatures between 156.6 - 660 C.',
                          'crucible_type': 'Al2O3 crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': np.nan,
                          'carrier_gas_type': 'Nitrogen',
                          'carrier_gas_flow': {'value': 40, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch TG 209 Libra',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMET', 'UMET_TGA_N2_7.csv')},
        'UMD_TGA_N2_avg': {'laboratory': 'University of Maryland',
                          'heating_rate': {'value': 10.0, 'unit': 'K/min'},
                          'temperature_program': {'initial_temperature': {'value': 313.0, 'unit': 'K'},
                                                  'isotherm': {'value': 1200.0, 'unit': 's'},
                                                  'max_temperature': {'value': 850.0, 'unit': 'K'}},
                          'initial_sample_mass': {'value': 4-7, 'unit': 'mg'},
                          'sample_geometry': 'powdered',
                          'calibration_type': 'Before each experiment, a baseline test was performed using an empty crucible. Temperature/Heat flow calibration were performed every 6 months using a set of 5 reference materials with melting temperatures between 60-820 C.',
                          'crucible_type': 'Pt-Rh crucibles',
                          'crucible_volume': {'value': 85, 'unit': 'µL'},
                          'crucible_lids': True,
                          'carrier_gas_type': 'Ultra High Purity (UHP) Nitrogen',
                          'carrier_gas_flow': {'value': 50, 'unit': 'ml/min'},
                          'instrument_type': 'Netzsch F3 Jupiter was used to conduct Simultaneous Thermal Analysis (TGA + DSC) experiments',
                          'path': os.path.join('Non-charring', 'PMMA', 'UMD', 'UMD_TGA.csv')},
        }, 
                'Gasification': {
                    'FM_Gasification_25kWm2_1': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 25.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 168.332879, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_25kWm2_1.csv')},
                    'FM_Gasification_25kWm2_2': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 25.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 168.479587, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_25kWm2_2.csv')},
                    'FM_Gasification_25kWm2_3': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 25.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 168.263386, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_25kWm2_3.csv')},
                    'FM_Gasification_50kWm2_1': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 50.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 168.009602, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_50kWm2_1.csv')},
                    'FM_Gasification_50kWm2_2': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 50.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 167.831299, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_50kWm2_2.csv')},
                    'FM_Gasification_50kWm2_3': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 50.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 167.404452, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_50kWm2_3.csv')},
                    'FM_Gasification_65kWm2_1': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 65.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 169.489286, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_65kWm2_1.csv')},
                    'FM_Gasification_65kWm2_2': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 65.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 166.066022, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_65kWm2_2.csv')},
                    'FM_Gasification_65kWm2_3': {
                        'laboratory': 'FM',
                        'radiative_flux': {'value': 65.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': 168.190993, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.6, 'unit': 'cm'},
                        'edge_length': {'value': 9.52, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'side and bottom',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': None, 'unit': 'cm'},
                        'back_side': None,
                        'sample_temperature_location': 'front',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'exhaust_gas_flow': {'value': None, 'unit': 'l/min'},
                        'instrument_type': 'Cone Calorimeter',
                        'path': os.path.join('Non-charring', 'PMMA', 'FM', 'FM_Gasification_65kWm2_3.csv')},
                    
                    'UMD_CAPA_25kWm2_MLR': {
                        'laboratory': 'UMD',
                        'radiative_flux': {'value': 25.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': None, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.58, 'unit': 'cm'},
                        'edge_length': {'value': 7.00, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'around the side',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': 1.00, 'unit': 'cm'},
                        'back_side': 'exposed, copper foil, high emissivity paint (alpha = 0.95)',
                        'sample_temperature_location': 'back',
                        'temperature_measurement': 'IR camera, four radial locations (r=0, 0.01, 0.02, 0.03)m',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'carrier_gas_flow': {'value': 185.0, 'unit': 'SLPM'},
                        'exhaust_gas_flow': {'value': 175.0, 'unit': 'l/s'}, 
                        'convection_coeff_front': {'value': 8.6, 'unit': 'W/(m^2 K)'},
                        'convection_coeff_back': {'value': 4.0, 'unit': 'W/(m^2 K)'},
                        'gas_temperature_front': {'value': 330.0, 'unit': 'K'},
                        'gas_temperature_back': {'value': 300.0, 'unit': 'K'},
                        'absorption_coeff': {'value': 2.38, 'unit': 'm^2/kg'},
                        'instrument_type': 'CAPA II',
                        'path': os.path.join('Non-charring', 'PMMA', 'UMD', 'UMD_CAPA_25kWm2_MLR.csv')},
                    'UMD_CAPA_25kWm2_Temp': {
                        'laboratory': 'UMD',
                        'radiative_flux': {'value': 25.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': None, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.58, 'unit': 'cm'},
                        'edge_length': {'value': 7.00, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'around the side',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': 1.00, 'unit': 'cm'},
                        'back_side': 'exposed, copper foil, high emissivity paint (alpha = 0.95)',
                        'sample_temperature_location': 'back',
                        'temperature_measurement': 'IR camera, four radial locations (r=0, 0.01, 0.02, 0.03)m',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'carrier_gas_flow': {'value': 185.0, 'unit': 'SLPM'},
                        'exhaust_gas_flow': {'value': 175.0, 'unit': 'l/s'}, 
                        'convection_coeff_front': {'value': 8.6, 'unit': 'W/(m^2 K)'},
                        'convection_coeff_back': {'value': 4.0, 'unit': 'W/(m^2 K)'},
                        'gas_temperature_front': {'value': 330.0, 'unit': 'K'},
                        'gas_temperature_back': {'value': 300.0, 'unit': 'K'},
                        'absorption_coeff': {'value': 2.38, 'unit': 'm^2/kg'},
                        'instrument_type': 'CAPA II',
                        'path': os.path.join('Non-charring', 'PMMA', 'UMD', 'UMD_CAPA_25kWm2_Temp.csv')},
                    
                'UMD_CAPA_60kWm2_MLR': {
                        'laboratory': 'UMD',
                        'radiative_flux': {'value': 60.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': None, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.58, 'unit': 'cm'},
                        'edge_length': {'value': 7.00, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'around the side',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': 1.00, 'unit': 'cm'},
                        'back_side': 'exposed, copper foil, high emissivity paint (alpha = 0.95)',
                        'sample_temperature_location': 'back',
                        'temperature_measurement': 'IR camera, four radial locations (r=0, 0.01, 0.02, 0.03)m',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'carrier_gas_flow': {'value': 185.0, 'unit': 'SLPM'},
                        'exhaust_gas_flow': {'value': 175.0, 'unit': 'l/s'}, 
                        'convection_coeff_front': {'value': 8.6, 'unit': 'W/(m^2 K)'},
                        'convection_coeff_back': {'value': 4.0, 'unit': 'W/(m^2 K)'},
                        'gas_temperature_front': {'value': 330.0, 'unit': 'K'},
                        'gas_temperature_back': {'value': 300.0, 'unit': 'K'},
                        'absorption_coeff': {'value': 2.38, 'unit': 'm^2/kg'},
                        'instrument_type': 'CAPA II',
                        'path': os.path.join('Non-charring', 'PMMA', 'UMD', 'UMD_CAPA_60kWm2_MLR.csv')},
                    'UMD_CAPA_60kWm2_Temp': {
                        'laboratory': 'UMD',
                        'radiative_flux': {'value': 60.0, 'unit': 'KW/m2'},
                        'heater_temperature': {'value': None, 'unit': 'K'},
                        'initial_sample_mass': {'value': None, 'unit': 'g'},
                        'sample_geometry': 'round',
                        'sample_thickness': {'value': 0.58, 'unit': 'cm'},
                        'edge_length': {'value': 7.00, 'unit': 'cm'},
                        'sample_orientation': 'horizontal',
                        'insulation_location': 'around the side',
                        'insulation_type': None, 
                        'insulation_material': None,
                        'insulation_thickness': {'value': 1.00, 'unit': 'cm'},
                        'back_side': 'exposed, copper foil, high emissivity paint (alpha = 0.95)',
                        'sample_temperature_location': 'back',
                        'temperature_measurement': 'IR camera, four radial locations (r=0, 0.01, 0.02, 0.03)m',
                        'calibration_type': None,
                        'carrier_gas_type': 'Nitrogen',
                        'carrier_gas_flow': {'value': 185.0, 'unit': 'SLPM'},
                        'exhaust_gas_flow': {'value': 175.0, 'unit': 'l/s'}, 
                        'convection_coeff_front': {'value': 8.6, 'unit': 'W/(m^2 K)'},
                        'convection_coeff_back': {'value': 4.0, 'unit': 'W/(m^2 K)'},
                        'gas_temperature_front': {'value': 330.0, 'unit': 'K'},
                        'gas_temperature_back': {'value': 300.0, 'unit': 'K'},
                        'absorption_coeff': {'value': 2.38, 'unit': 'm^2/kg'},
                        'instrument_type': 'CAPA II',
                        'path': os.path.join('Non-charring', 'PMMA', 'UMD', 'UMD_CAPA_60kWm2_Temp.csv')},}
               }
                                       
                                       
